[package]
name = "rustcm-cli"
version = "0.1.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orion = "0.17.4"
passterm = "1.1.7"
colored = "2.0.0"
