[package]
name = "rustcm-cli"
version = "0.2.0"
edition = "2021"

[lib]
name = "rscm"
path = "src/lib.rs"

[[bin]]
name = "rscm"
path = "src/main.rs"

[dependencies]
orion = { version = "0.17", features = ["safe_api"] }
argon2 = "0.5"
clap = { version = "4", features = ["derive"] }
thiserror = "1.0"
colored = "2.0"
passterm = "2.0"
zeroize = "1.7"
