[package]
name = "rustcm-cli"
version = "0.1.3-alpha"
edition = "2021"

[lib]
name = "rustcm_cli"
path = "src/lib.rs"

[[bin]]
name = "rustcm-cli"
path = "src/main.rs"

[dependencies]
orion = "0.17.5"
passterm = "2.0.0"
colored = "2.0.4"
